### ISSUE TITLE
Oo

### ISSUE THREAD

**Issue by Moredread** [untoldwind/moredread#1]
I feel offended!!!

Just kidding :p What was this project about?

**Comment by untoldwind** [comment]
This was one of my one-shot projects: Is it possible to create some 3D-Modelling using JAVA/SWT/OpenGL (lwjgl in this case) ... and if you can, why shouldn't you ;)
Answer I this case is: Yes, in theory you can.

But as you can see I have not picked up on that idea for a very long time now. I mostly keep this project for reference. I think deep down in there is some okayish mesh generators and 3D boolean operators.
